-- alter.test
-- 
-- execsql {
--     CREATE TABLE t2(a INTEGER);
--     INSERT INTO t2 VALUES(1);
--     INSERT INTO t2 VALUES(1);
--     INSERT INTO t2 VALUES(2);
--     ALTER TABLE t2 ADD COLUMN b INTEGER DEFAULT 9;
--     SELECT sum(b) FROM t2;
-- }
CREATE TABLE t2(a INTEGER);
INSERT INTO t2 VALUES(1);
INSERT INTO t2 VALUES(1);
INSERT INTO t2 VALUES(2);
ALTER TABLE t2 ADD COLUMN b INTEGER DEFAULT 9;
SELECT sum(b) FROM t2;