-- alter.test
-- 
-- execsql {
--     SELECT SQLITE_RENAME_TABLE(0,0);
--     SELECT SQLITE_RENAME_TABLE(10,20);
--     SELECT SQLITE_RENAME_TABLE('foo', 'foo');
-- }
SELECT SQLITE_RENAME_TABLE(0,0);
SELECT SQLITE_RENAME_TABLE(10,20);
SELECT SQLITE_RENAME_TABLE('foo', 'foo');