-- alter.test
-- 
-- execsql {
--     CREATE TABLE tbl1(a INTEGER PRIMARY KEY AUTOINCREMENT);
--     INSERT INTO tbl1 VALUES(10);
-- }
CREATE TABLE tbl1(a INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO tbl1 VALUES(10);