-- autoinc.test
-- 
-- execsql {
--       CREATE TABLE t4(m INTEGER PRIMARY KEY AUTOINCREMENT, n);
--       CREATE TABLE t5(o, p INTEGER PRIMARY KEY AUTOINCREMENT);
-- }
CREATE TABLE t4(m INTEGER PRIMARY KEY AUTOINCREMENT, n);
CREATE TABLE t5(o, p INTEGER PRIMARY KEY AUTOINCREMENT);