-- autoinc.test
-- 
-- db eval {
--     CREATE TABLE t2(x INTEGER PRIMARY KEY AUTOINCREMENT, y);
--     INSERT INTO t2 VALUES(NULL, 1);
--     CREATE TABLE t3(a INTEGER PRIMARY KEY AUTOINCREMENT, b);
--     INSERT INTO t3 SELECT * FROM t2 WHERE y>1;
-- 
--     SELECT * FROM sqlite_sequence WHERE name='t3';
-- }
CREATE TABLE t2(x INTEGER PRIMARY KEY AUTOINCREMENT, y);
INSERT INTO t2 VALUES(NULL, 1);
CREATE TABLE t3(a INTEGER PRIMARY KEY AUTOINCREMENT, b);
INSERT INTO t3 SELECT * FROM t2 WHERE y>1;
SELECT * FROM sqlite_sequence WHERE name='t3';