-- autoinc.test
-- 
-- execsql {
--       INSERT INTO t1 VALUES(10,1);
--       INSERT INTO t3 VALUES(20,2);
--       INSERT INTO t1 VALUES(NULL,3);
--       INSERT INTO t3 VALUES(NULL,4);
-- }
INSERT INTO t1 VALUES(10,1);
INSERT INTO t3 VALUES(20,2);
INSERT INTO t1 VALUES(NULL,3);
INSERT INTO t3 VALUES(NULL,4);