-- conflict.test
-- 
-- execsql {
--     PRAGMA count_changes=0;
--     CREATE TABLE t2(
--       a INTEGER UNIQUE ON CONFLICT IGNORE,
--       b INTEGER UNIQUE ON CONFLICT FAIL,
--       c INTEGER UNIQUE ON CONFLICT REPLACE,
--       d INTEGER UNIQUE ON CONFLICT ABORT,
--       e INTEGER UNIQUE ON CONFLICT ROLLBACK
--     );
--     CREATE TABLE t3(x);
--     INSERT INTO t3 VALUES(1);
--     SELECT * FROM t3;
-- }
PRAGMA count_changes=0;
CREATE TABLE t2(
a INTEGER UNIQUE ON CONFLICT IGNORE,
b INTEGER UNIQUE ON CONFLICT FAIL,
c INTEGER UNIQUE ON CONFLICT REPLACE,
d INTEGER UNIQUE ON CONFLICT ABORT,
e INTEGER UNIQUE ON CONFLICT ROLLBACK
);
CREATE TABLE t3(x);
INSERT INTO t3 VALUES(1);
SELECT * FROM t3;