-- delete.test
-- 
-- execsql {
--     DELETE FROM t5;
--     INSERT INTO t5 VALUES(1, 2);
--     INSERT INTO t5 VALUES(3, 4);
--     INSERT INTO t5 VALUES(5, 6);
-- }
DELETE FROM t5;
INSERT INTO t5 VALUES(1, 2);
INSERT INTO t5 VALUES(3, 4);
INSERT INTO t5 VALUES(5, 6);