-- descidx1.test
-- 
-- execsql {
--     CREATE TABLE t1(a,b,c);
--     CREATE INDEX i1 ON t1(a ASC, b DESC, c ASC);
--     INSERT INTO t1 VALUES(1,2,3);
--     INSERT INTO t1 VALUES(1,1,0);
--     INSERT INTO t1 VALUES(1,2,1);
--     INSERT INTO t1 VALUES(1,3,4);
-- }
CREATE TABLE t1(a,b,c);
CREATE INDEX i1 ON t1(a ASC, b DESC, c ASC);
INSERT INTO t1 VALUES(1,2,3);
INSERT INTO t1 VALUES(1,1,0);
INSERT INTO t1 VALUES(1,2,1);
INSERT INTO t1 VALUES(1,3,4);