-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE p1(a, b UNIQUE);
--     CREATE TABLE c1(c REFERENCES p1(b) ON DELETE CASCADE, d);
--     INSERT INTO p1 VALUES(NULL, NULL);
--     INSERT INTO p1 VALUES(4, 4);
--     INSERT INTO p1 VALUES(5, 5);
--     INSERT INTO c1 VALUES(NULL, NULL);
--     INSERT INTO c1 VALUES(4, 4);
--     INSERT INTO c1 VALUES(5, 5);
--     SELECT count(*) FROM c1;
-- }
CREATE TABLE p1(a, b UNIQUE);
CREATE TABLE c1(c REFERENCES p1(b) ON DELETE CASCADE, d);
INSERT INTO p1 VALUES(NULL, NULL);
INSERT INTO p1 VALUES(4, 4);
INSERT INTO p1 VALUES(5, 5);
INSERT INTO c1 VALUES(NULL, NULL);
INSERT INTO c1 VALUES(4, 4);
INSERT INTO c1 VALUES(5, 5);
SELECT count(*) FROM c1;