-- e_fkey.test
-- 
-- execsql { 
--     DELETE FROM c1 ; DELETE FROM c2 ; DELETE FROM c3 ;
--     DELETE FROM c4 ; DELETE FROM c5 ; DELETE FROM c6 ;
--     DELETE FROM c7 
-- }
DELETE FROM c1 ; DELETE FROM c2 ; DELETE FROM c3 ;
DELETE FROM c4 ; DELETE FROM c5 ; DELETE FROM c6 ;
DELETE FROM c7