-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE pA(x PRIMARY KEY);
--     CREATE TABLE cA(c REFERENCES pA ON DELETE SET NULL);
--     CREATE TABLE cB(c REFERENCES pA ON UPDATE SET NULL);
-- 
--     INSERT INTO pA VALUES(X'ABCD');
--     INSERT INTO pA VALUES(X'1234');
--     INSERT INTO cA VALUES(X'ABCD');
--     INSERT INTO cB VALUES(X'1234');
-- }
CREATE TABLE pA(x PRIMARY KEY);
CREATE TABLE cA(c REFERENCES pA ON DELETE SET NULL);
CREATE TABLE cB(c REFERENCES pA ON UPDATE SET NULL);
INSERT INTO pA VALUES(X'ABCD');
INSERT INTO pA VALUES(X'1234');
INSERT INTO cA VALUES(X'ABCD');
INSERT INTO cB VALUES(X'1234');