-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE p(a, b, PRIMARY KEY(a, b));
-- 
--     CREATE TABLE c1(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE SET NULL);
--     CREATE TABLE c2(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE SET DEFAULT);
--     CREATE TABLE c3(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE CASCADE);
--     CREATE TABLE c4(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE RESTRICT);
--     CREATE TABLE c5(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE NO ACTION);
-- 
--     CREATE TABLE c6(c, d, 
--       FOREIGN KEY(c, d) REFERENCES p ON DELETE RESTRICT 
--       DEFERRABLE INITIALLY DEFERRED
--     );
--     CREATE TABLE c7(c, d, 
--       FOREIGN KEY(c, d) REFERENCES p ON DELETE NO ACTION
--       DEFERRABLE INITIALLY DEFERRED
--     );
-- 
--     CREATE TABLE log(msg);
--     CREATE TRIGGER tt AFTER DELETE ON p BEGIN
--       INSERT INTO log VALUES('delete ' || old.rowid);
--     END;
-- }
CREATE TABLE p(a, b, PRIMARY KEY(a, b));
CREATE TABLE c1(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE SET NULL);
CREATE TABLE c2(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE SET DEFAULT);
CREATE TABLE c3(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE CASCADE);
CREATE TABLE c4(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE RESTRICT);
CREATE TABLE c5(c, d, FOREIGN KEY(c, d) REFERENCES p ON DELETE NO ACTION);
CREATE TABLE c6(c, d, 
FOREIGN KEY(c, d) REFERENCES p ON DELETE RESTRICT 
DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE c7(c, d, 
FOREIGN KEY(c, d) REFERENCES p ON DELETE NO ACTION
DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE log(msg);
CREATE TRIGGER tt AFTER DELETE ON p BEGIN
INSERT INTO log VALUES('delete ' || old.rowid);
END;