-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE t1(a PRIMARY KEY,
--       b REFERENCES t1 DEFERRABLE INITIALLY DEFERRED
--     );
--     INSERT INTO t1 VALUES(1, 1);
--     INSERT INTO t1 VALUES(2, 2);
--     INSERT INTO t1 VALUES(3, 3);
-- }
CREATE TABLE t1(a PRIMARY KEY,
b REFERENCES t1 DEFERRABLE INITIALLY DEFERRED
);
INSERT INTO t1 VALUES(1, 1);
INSERT INTO t1 VALUES(2, 2);
INSERT INTO t1 VALUES(3, 3);