-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE t1(a NUMERIC PRIMARY KEY);
--     CREATE TABLE t2(b TEXT REFERENCES t1);
-- }
CREATE TABLE t1(a NUMERIC PRIMARY KEY);
CREATE TABLE t2(b TEXT REFERENCES t1);