-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE parent(x PRIMARY KEY);
--     CREATE TABLE child1(c REFERENCES parent ON UPDATE RESTRICT
--       DEFERRABLE INITIALLY DEFERRED
--     );
--     CREATE TABLE child2(c REFERENCES parent ON UPDATE NO ACTION
--       DEFERRABLE INITIALLY DEFERRED
--     );
-- 
--     INSERT INTO parent VALUES('key1');
--     INSERT INTO parent VALUES('key2');
--     INSERT INTO child1 VALUES('key1');
--     INSERT INTO child2 VALUES('key2');
--     BEGIN;
-- }
CREATE TABLE parent(x PRIMARY KEY);
CREATE TABLE child1(c REFERENCES parent ON UPDATE RESTRICT
DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE child2(c REFERENCES parent ON UPDATE NO ACTION
DEFERRABLE INITIALLY DEFERRED
);
INSERT INTO parent VALUES('key1');
INSERT INTO parent VALUES('key2');
INSERT INTO child1 VALUES('key1');
INSERT INTO child2 VALUES('key2');
BEGIN;