-- e_fkey.test
-- 
-- execsql {
--     CREATE TABLE p(a, b, PRIMARY KEY(a, b));
--     CREATE TABLE cd(c, d, 
--       FOREIGN KEY(c, d) REFERENCES p DEFERRABLE INITIALLY DEFERRED);
--     CREATE TABLE ci(c, d, 
--       FOREIGN KEY(c, d) REFERENCES p DEFERRABLE INITIALLY IMMEDIATE);
--     BEGIN;
-- }
CREATE TABLE p(a, b, PRIMARY KEY(a, b));
CREATE TABLE cd(c, d, 
FOREIGN KEY(c, d) REFERENCES p DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE ci(c, d, 
FOREIGN KEY(c, d) REFERENCES p DEFERRABLE INITIALLY IMMEDIATE);
BEGIN;