-- fkey2.test
-- 
-- execsql {
--     DROP TABLE t2;
--     CREATE TABLE t2(y REFERENCES t1 ON DELETE RESTRICT);
--     INSERT INTO t2 VALUES('a');
--     INSERT INTO t2 VALUES('b');
-- }
DROP TABLE t2;
CREATE TABLE t2(y REFERENCES t1 ON DELETE RESTRICT);
INSERT INTO t2 VALUES('a');
INSERT INTO t2 VALUES('b');