-- fkey2.test
-- 
-- execsql {
--       CREATE TABLE t1(a PRIMARY KEY, b REFERENCES t1);
--       CREATE TABLE t2(a PRIMARY KEY, b REFERENCES t1, c REFERENCES t2);
--       CREATE TABLE t3(a REFERENCES t1, b REFERENCES t2, c REFERENCES t1);
-- }
CREATE TABLE t1(a PRIMARY KEY, b REFERENCES t1);
CREATE TABLE t2(a PRIMARY KEY, b REFERENCES t1, c REFERENCES t2);
CREATE TABLE t3(a REFERENCES t1, b REFERENCES t2, c REFERENCES t1);