-- fkey2.test
-- 
-- execsql {
--     CREATE TABLE t1(a, b PRIMARY KEY);
--     CREATE TABLE t2(
--       x REFERENCES t1 ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED 
--     );
--     INSERT INTO t1 VALUES(1, 'one');
--     INSERT INTO t1 VALUES(2, 'two');
--     INSERT INTO t1 VALUES(3, 'three');
-- }
CREATE TABLE t1(a, b PRIMARY KEY);
CREATE TABLE t2(
x REFERENCES t1 ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED 
);
INSERT INTO t1 VALUES(1, 'one');
INSERT INTO t1 VALUES(2, 'two');
INSERT INTO t1 VALUES(3, 'three');