-- in.test
-- 
-- execsql {
--     BEGIN TRANSACTION;
--     CREATE TABLE a(id INTEGER);
--     INSERT INTO a VALUES(1);
--     INSERT INTO a VALUES(2);
--     INSERT INTO a VALUES(3);
--     CREATE TABLE b(id INTEGER);
--     INSERT INTO b VALUES(NULL);
--     INSERT INTO b VALUES(3);
--     INSERT INTO b VALUES(4);
--     INSERT INTO b VALUES(5);
--     COMMIT;
--     SELECT * FROM a WHERE id NOT IN (SELECT id FROM b);
-- }
BEGIN TRANSACTION;
CREATE TABLE a(id INTEGER);
INSERT INTO a VALUES(1);
INSERT INTO a VALUES(2);
INSERT INTO a VALUES(3);
CREATE TABLE b(id INTEGER);
INSERT INTO b VALUES(NULL);
INSERT INTO b VALUES(3);
INSERT INTO b VALUES(4);
INSERT INTO b VALUES(5);
COMMIT;
SELECT * FROM a WHERE id NOT IN (SELECT id FROM b);