-- in3.test
-- 
-- execsql {
--     CREATE TABLE t1(a PRIMARY KEY, b);
--     INSERT INTO t1 VALUES(1, 2);
--     INSERT INTO t1 VALUES(3, 4);
--     INSERT INTO t1 VALUES(5, 6);
-- }
CREATE TABLE t1(a PRIMARY KEY, b);
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
INSERT INTO t1 VALUES(5, 6);