-- in4.test
-- 
-- execsql {
--     DROP TABLE IF EXISTS t1;
--     DROP TABLE IF EXISTS t2;
--     CREATE TABLE t1(x, id);
--     CREATE TABLE t2(x, id);
--     INSERT INTO t1 VALUES(NULL, NULL);
--     INSERT INTO t1 VALUES(0, NULL);
--     INSERT INTO t1 VALUES(1, 3);
--     INSERT INTO t1 VALUES(2, 4);
--     INSERT INTO t1 VALUES(3, 5);
--     INSERT INTO t1 VALUES(4, 6);
--     INSERT INTO t2 VALUES(0, NULL);
--     INSERT INTO t2 VALUES(4, 1);
--     INSERT INTO t2 VALUES(NULL, 1);
--     INSERT INTO t2 VALUES(NULL, NULL);
-- }
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
CREATE TABLE t1(x, id);
CREATE TABLE t2(x, id);
INSERT INTO t1 VALUES(NULL, NULL);
INSERT INTO t1 VALUES(0, NULL);
INSERT INTO t1 VALUES(1, 3);
INSERT INTO t1 VALUES(2, 4);
INSERT INTO t1 VALUES(3, 5);
INSERT INTO t1 VALUES(4, 6);
INSERT INTO t2 VALUES(0, NULL);
INSERT INTO t2 VALUES(4, 1);
INSERT INTO t2 VALUES(NULL, 1);
INSERT INTO t2 VALUES(NULL, NULL);