-- index.test
-- 
-- execsql {
--     CREATE TABLE t4(a NUM,b);
--     INSERT INTO t4 VALUES('0.0',1);
--     INSERT INTO t4 VALUES('0.00',2);
--     INSERT INTO t4 VALUES('abc',3);
--     INSERT INTO t4 VALUES('-1.0',4);
--     INSERT INTO t4 VALUES('+1.0',5);
--     INSERT INTO t4 VALUES('0',6);
--     INSERT INTO t4 VALUES('00000',7);
--     SELECT a FROM t4 ORDER BY b;
-- }
CREATE TABLE t4(a NUM,b);
INSERT INTO t4 VALUES('0.0',1);
INSERT INTO t4 VALUES('0.00',2);
INSERT INTO t4 VALUES('abc',3);
INSERT INTO t4 VALUES('-1.0',4);
INSERT INTO t4 VALUES('+1.0',5);
INSERT INTO t4 VALUES('0',6);
INSERT INTO t4 VALUES('00000',7);
SELECT a FROM t4 ORDER BY b;