-- index.test
-- 
-- execsql {
--     DELETE FROM t1;
--     INSERT INTO t1 VALUES (1,1);
--     INSERT INTO t1 VALUES (1,2);
--     INSERT INTO t1 VALUES (1,3);
--     INSERT INTO t1 VALUES (1,4);
--     INSERT INTO t1 VALUES (1,5);
--     INSERT INTO t1 VALUES (1,6);
--     INSERT INTO t1 VALUES (1,7);
--     INSERT INTO t1 VALUES (1,8);
--     INSERT INTO t1 VALUES (1,9);
--     INSERT INTO t1 VALUES (2,0);
--     SELECT b FROM t1 WHERE a=1 ORDER BY b;
-- }
DELETE FROM t1;
INSERT INTO t1 VALUES (1,1);
INSERT INTO t1 VALUES (1,2);
INSERT INTO t1 VALUES (1,3);
INSERT INTO t1 VALUES (1,4);
INSERT INTO t1 VALUES (1,5);
INSERT INTO t1 VALUES (1,6);
INSERT INTO t1 VALUES (1,7);
INSERT INTO t1 VALUES (1,8);
INSERT INTO t1 VALUES (1,9);
INSERT INTO t1 VALUES (2,0);
SELECT b FROM t1 WHERE a=1 ORDER BY b;