-- index.test
-- 
-- execsql {
--       CREATE TABLE t7(a UNIQUE PRIMARY KEY);
--       CREATE TABLE t8(a UNIQUE PRIMARY KEY ON CONFLICT ROLLBACK);
--       INSERT INTO t7 VALUES(1);
--       INSERT INTO t8 VALUES(1);
-- }
CREATE TABLE t7(a UNIQUE PRIMARY KEY);
CREATE TABLE t8(a UNIQUE PRIMARY KEY ON CONFLICT ROLLBACK);
INSERT INTO t7 VALUES(1);
INSERT INTO t8 VALUES(1);