-- insert3.test
-- 
-- execsql {
--     DELETE FROM t2dup;
--     INSERT INTO t2(a) SELECT 1 FROM t1 LIMIT 1;
--     INSERT INTO t2(b) SELECT 987 FROM t1 LIMIT 1;
--     INSERT INTO t2(c) SELECT 876 FROM t1 LIMIT 1;
--     SELECT * FROM t2dup;
-- }
DELETE FROM t2dup;
INSERT INTO t2(a) SELECT 1 FROM t1 LIMIT 1;
INSERT INTO t2(b) SELECT 987 FROM t1 LIMIT 1;
INSERT INTO t2(c) SELECT 876 FROM t1 LIMIT 1;
SELECT * FROM t2dup;