-- insert5.test
-- 
-- execsql {
--     CREATE TABLE MAIN(Id INTEGER, Id1 INTEGER); 
--     CREATE TABLE B(Id INTEGER, Id1 INTEGER); 
--     CREATE VIEW v1 AS SELECT * FROM B;
--     CREATE VIEW v2 AS SELECT * FROM MAIN;
--     INSERT INTO MAIN(Id,Id1) VALUES(2,3); 
--     INSERT INTO B(Id,Id1) VALUES(2,3); 
-- }
CREATE TABLE MAIN(Id INTEGER, Id1 INTEGER); 
CREATE TABLE B(Id INTEGER, Id1 INTEGER); 
CREATE VIEW v1 AS SELECT * FROM B;
CREATE VIEW v2 AS SELECT * FROM MAIN;
INSERT INTO MAIN(Id,Id1) VALUES(2,3); 
INSERT INTO B(Id,Id1) VALUES(2,3);