-- intarray.test
-- 
-- db eval {
--     CREATE TABLE t2(x INTEGER PRIMARY KEY, y);
--     INSERT INTO t2 SELECT * FROM t1;
--     SELECT b FROM t1 WHERE a IN (12,34,56,78) ORDER BY a
-- }
CREATE TABLE t2(x INTEGER PRIMARY KEY, y);
INSERT INTO t2 SELECT * FROM t1;
SELECT b FROM t1 WHERE a IN (12,34,56,78) ORDER BY a