-- join6.test
-- 
-- execsql {
--     SELECT * FROM t1 NATURAL JOIN
--        (SELECT 3 AS b, 92 AS y, 93 AS z UNION SELECT 4, 94, 95)
--        NATURAL JOIN t3
-- }
SELECT * FROM t1 NATURAL JOIN
(SELECT 3 AS b, 92 AS y, 93 AS z UNION SELECT 4, 94, 95)
NATURAL JOIN t3