-- join.test
-- 
-- execsql {
--     CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT);
--     CREATE TABLE t2(a INTEGER PRIMARY KEY, b TEXT);
--     INSERT INTO t1 VALUES(1,'abc');
--     INSERT INTO t1 VALUES(2,'def');
--     INSERT INTO t2 VALUES(1,'abc');
--     INSERT INTO t2 VALUES(2,'def');
--     SELECT * FROM t1 NATURAL JOIN t2;
-- }
CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT);
CREATE TABLE t2(a INTEGER PRIMARY KEY, b TEXT);
INSERT INTO t1 VALUES(1,'abc');
INSERT INTO t1 VALUES(2,'def');
INSERT INTO t2 VALUES(1,'abc');
INSERT INTO t2 VALUES(2,'def');
SELECT * FROM t1 NATURAL JOIN t2;