-- join.test
-- 
-- execsql {
--     BEGIN;
--     CREATE TABLE t9(a INTEGER PRIMARY KEY, b);
--     INSERT INTO t9 VALUES(1,11);
--     INSERT INTO t9 VALUES(2,22);
--     CREATE TABLE t10(x INTEGER PRIMARY KEY, y);
--     INSERT INTO t10 VALUES(1,2);
--     INSERT INTO t10 VALUES(3,3);    
--     CREATE TABLE t11(p INTEGER PRIMARY KEY, q);
--     INSERT INTO t11 VALUES(2,111);
--     INSERT INTO t11 VALUES(3,333);    
--     CREATE VIEW v10_11 AS SELECT x, q FROM t10, t11 WHERE t10.y=t11.p;
--     COMMIT;
--     SELECT * FROM t9 LEFT JOIN v10_11 ON( a=x );
-- }
BEGIN;
CREATE TABLE t9(a INTEGER PRIMARY KEY, b);
INSERT INTO t9 VALUES(1,11);
INSERT INTO t9 VALUES(2,22);
CREATE TABLE t10(x INTEGER PRIMARY KEY, y);
INSERT INTO t10 VALUES(1,2);
INSERT INTO t10 VALUES(3,3);    
CREATE TABLE t11(p INTEGER PRIMARY KEY, q);
INSERT INTO t11 VALUES(2,111);
INSERT INTO t11 VALUES(3,333);    
CREATE VIEW v10_11 AS SELECT x, q FROM t10, t11 WHERE t10.y=t11.p;
COMMIT;
SELECT * FROM t9 LEFT JOIN v10_11 ON( a=x );