-- like.test
-- 
-- execsql {
--     CREATE TABLE t2(x TEXT COLLATE NOCASE);
--     INSERT INTO t2 SELECT * FROM t1;
--     CREATE INDEX i2 ON t2(x COLLATE NOCASE);
-- }
CREATE TABLE t2(x TEXT COLLATE NOCASE);
INSERT INTO t2 SELECT * FROM t1;
CREATE INDEX i2 ON t2(x COLLATE NOCASE);