-- limit.test
-- 
-- execsql {
--       BEGIN;
--       CREATE TABLE t3(x);
--       INSERT INTO t3 SELECT x FROM t1 ORDER BY x LIMIT 10 OFFSET 1;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
--       END;
--       SELECT count(*) FROM t3;
-- }
BEGIN;
CREATE TABLE t3(x);
INSERT INTO t3 SELECT x FROM t1 ORDER BY x LIMIT 10 OFFSET 1;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
INSERT INTO t3 SELECT x+(SELECT max(x) FROM t3) FROM t3;
END;
SELECT count(*) FROM t3;