-- memdb.test
-- 
-- execsql {
--       CREATE TABLE t6(x);
--       INSERT INTO t6 VALUES(1);
--       INSERT INTO t6 SELECT x+1 FROM t6;
--       INSERT INTO t6 SELECT x+2 FROM t6;
--       INSERT INTO t6 SELECT x+4 FROM t6;
--       INSERT INTO t6 SELECT x+8 FROM t6;
--       INSERT INTO t6 SELECT x+16 FROM t6;
--       INSERT INTO t6 SELECT x+32 FROM t6;
--       INSERT INTO t6 SELECT x+64 FROM t6;
--       INSERT INTO t6 SELECT x+128 FROM t6;
--       SELECT count(*) FROM (SELECT DISTINCT x FROM t6);
-- }
CREATE TABLE t6(x);
INSERT INTO t6 VALUES(1);
INSERT INTO t6 SELECT x+1 FROM t6;
INSERT INTO t6 SELECT x+2 FROM t6;
INSERT INTO t6 SELECT x+4 FROM t6;
INSERT INTO t6 SELECT x+8 FROM t6;
INSERT INTO t6 SELECT x+16 FROM t6;
INSERT INTO t6 SELECT x+32 FROM t6;
INSERT INTO t6 SELECT x+64 FROM t6;
INSERT INTO t6 SELECT x+128 FROM t6;
SELECT count(*) FROM (SELECT DISTINCT x FROM t6);