-- memdb.test
-- 
-- execsql {
--     DROP TABLE t2;
--     DROP TABLE t3;
--     CREATE TABLE t2(a,b,c);
--     INSERT INTO t2 VALUES(1,2,1);
--     INSERT INTO t2 VALUES(2,3,2);
--     INSERT INTO t2 VALUES(3,4,1);
--     INSERT INTO t2 VALUES(4,5,4);
--     SELECT c FROM t2 ORDER BY b;
--     CREATE TABLE t3(x);
--     INSERT INTO t3 VALUES(1);
-- }
DROP TABLE t2;
DROP TABLE t3;
CREATE TABLE t2(a,b,c);
INSERT INTO t2 VALUES(1,2,1);
INSERT INTO t2 VALUES(2,3,2);
INSERT INTO t2 VALUES(3,4,1);
INSERT INTO t2 VALUES(4,5,4);
SELECT c FROM t2 ORDER BY b;
CREATE TABLE t3(x);
INSERT INTO t3 VALUES(1);