-- minmax2.test
-- 
-- execsql {
--     CREATE TABLE t2(a INTEGER PRIMARY KEY, b);
--     INSERT INTO t2 SELECT * FROM t1;
-- }
CREATE TABLE t2(a INTEGER PRIMARY KEY, b);
INSERT INTO t2 SELECT * FROM t1;