-- minmax.test
-- 
-- execsql {
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     SELECT count(*) FROM t6;
-- }
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
SELECT count(*) FROM t6;