-- minmax3.test
-- 
-- execsql {
--     DROP TABLE t2;
--     CREATE TABLE t2(a, b);
--     CREATE INDEX i3 ON t2(a, b DESC);
--     INSERT INTO t2 VALUES(1, NULL);
--     INSERT INTO t2 VALUES(1, 1);
--     INSERT INTO t2 VALUES(1, 2);
--     INSERT INTO t2 VALUES(1, 3);
--     INSERT INTO t2 VALUES(2, NULL);
--     INSERT INTO t2 VALUES(2, 1);
--     INSERT INTO t2 VALUES(2, 2);
--     INSERT INTO t2 VALUES(2, 3);
--     INSERT INTO t2 VALUES(3, 1);
--     INSERT INTO t2 VALUES(3, 2);
--     INSERT INTO t2 VALUES(3, 3);
-- }
DROP TABLE t2;
CREATE TABLE t2(a, b);
CREATE INDEX i3 ON t2(a, b DESC);
INSERT INTO t2 VALUES(1, NULL);
INSERT INTO t2 VALUES(1, 1);
INSERT INTO t2 VALUES(1, 2);
INSERT INTO t2 VALUES(1, 3);
INSERT INTO t2 VALUES(2, NULL);
INSERT INTO t2 VALUES(2, 1);
INSERT INTO t2 VALUES(2, 2);
INSERT INTO t2 VALUES(2, 3);
INSERT INTO t2 VALUES(3, 1);
INSERT INTO t2 VALUES(3, 2);
INSERT INTO t2 VALUES(3, 3);