-- misc2.test
-- 
-- execsql {
--       DELETE FROM t1;
--       INSERT INTO t1 VALUES(1);
--       INSERT INTO t1 VALUES(2);
--       INSERT INTO t1 VALUES(3);
--       INSERT INTO t1 VALUES(4);
-- }
DELETE FROM t1;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);
INSERT INTO t1 VALUES(3);
INSERT INTO t1 VALUES(4);