-- misc3.test
-- 
-- execsql {
--     BEGIN;
--     CREATE TABLE y1(a);
--     CREATE TABLE y2(b);
--     CREATE TABLE y3(c);
--     CREATE TRIGGER r1 AFTER DELETE ON y1 FOR EACH ROW BEGIN
--       INSERT INTO y3(c) SELECT b FROM y2 ORDER BY b LIMIT 1;
--     END;
--     INSERT INTO y1 VALUES(1);
--     INSERT INTO y1 VALUES(2);
--     INSERT INTO y1 SELECT a+2 FROM y1;
--     INSERT INTO y1 SELECT a+4 FROM y1;
--     INSERT INTO y1 SELECT a+8 FROM y1;
--     INSERT INTO y1 SELECT a+16 FROM y1;
--     INSERT INTO y2 SELECT a FROM y1;
--     COMMIT;
--     SELECT count(*) FROM y1;
-- }
BEGIN;
CREATE TABLE y1(a);
CREATE TABLE y2(b);
CREATE TABLE y3(c);
CREATE TRIGGER r1 AFTER DELETE ON y1 FOR EACH ROW BEGIN
INSERT INTO y3(c) SELECT b FROM y2 ORDER BY b LIMIT 1;
END;
INSERT INTO y1 VALUES(1);
INSERT INTO y1 VALUES(2);
INSERT INTO y1 SELECT a+2 FROM y1;
INSERT INTO y1 SELECT a+4 FROM y1;
INSERT INTO y1 SELECT a+8 FROM y1;
INSERT INTO y1 SELECT a+16 FROM y1;
INSERT INTO y2 SELECT a FROM y1;
COMMIT;
SELECT count(*) FROM y1;