-- misc1.test
-- 
-- execsql {
--     CREATE TABLE t8(x TEXT COLLATE numeric, y INTEGER COLLATE text, z);
--     INSERT INTO t8 VALUES(0,0,1);
--     INSERT INTO t8 VALUES(0.0,0,2);
--     INSERT INTO t8 VALUES(0,0.0,3);
--     INSERT INTO t8 VALUES(0.0,0.0,4);
--     SELECT DISTINCT x, y FROM t8 ORDER BY z;
-- }
CREATE TABLE t8(x TEXT COLLATE numeric, y INTEGER COLLATE text, z);
INSERT INTO t8 VALUES(0,0,1);
INSERT INTO t8 VALUES(0.0,0,2);
INSERT INTO t8 VALUES(0,0.0,3);
INSERT INTO t8 VALUES(0.0,0.0,4);
SELECT DISTINCT x, y FROM t8 ORDER BY z;