-- notnull.test
-- 
-- execsql {
--     CREATE TABLE t1 (
--       a NOT NULL,
--       b NOT NULL DEFAULT 5,
--       c NOT NULL ON CONFLICT REPLACE DEFAULT 6,
--       d NOT NULL ON CONFLICT IGNORE DEFAULT 7,
--       e NOT NULL ON CONFLICT ABORT DEFAULT 8
--     );
--     SELECT * FROM t1;
-- }
CREATE TABLE t1 (
a NOT NULL,
b NOT NULL DEFAULT 5,
c NOT NULL ON CONFLICT REPLACE DEFAULT 6,
d NOT NULL ON CONFLICT IGNORE DEFAULT 7,
e NOT NULL ON CONFLICT ABORT DEFAULT 8
);
SELECT * FROM t1;