-- pagerfault.test
-- 
-- execsql {
--     PRAGMA auto_vacuum = FULL;
--     CREATE TABLE t1(x); INSERT INTO t1 VALUES(1);
--     CREATE TABLE t2(x); INSERT INTO t2 VALUES(2);
--     CREATE TABLE t3(x); INSERT INTO t3 VALUES(3);
--     CREATE TABLE t4(x); INSERT INTO t4 VALUES(4);
--     CREATE TABLE t5(x); INSERT INTO t5 VALUES(5);
--     CREATE TABLE t6(x); INSERT INTO t6 VALUES(6);
-- }
PRAGMA auto_vacuum = FULL;
CREATE TABLE t1(x); INSERT INTO t1 VALUES(1);
CREATE TABLE t2(x); INSERT INTO t2 VALUES(2);
CREATE TABLE t3(x); INSERT INTO t3 VALUES(3);
CREATE TABLE t4(x); INSERT INTO t4 VALUES(4);
CREATE TABLE t5(x); INSERT INTO t5 VALUES(5);
CREATE TABLE t6(x); INSERT INTO t6 VALUES(6);