-- pcache.test
-- 
-- execsql { 
--     SELECT * FROM t1 ORDER BY a; SELECT * FROM t1;
--     SELECT * FROM t2 ORDER BY a; SELECT * FROM t2;
--     SELECT * FROM t3 ORDER BY a; SELECT * FROM t3;
--     SELECT * FROM t4 ORDER BY a; SELECT * FROM t4;
--     SELECT * FROM t5 ORDER BY a; SELECT * FROM t5;
--     SELECT * FROM t6 ORDER BY a; SELECT * FROM t6;
--     SELECT * FROM t7 ORDER BY a; SELECT * FROM t7;
--     SELECT * FROM t8 ORDER BY a; SELECT * FROM t8;
--     SELECT * FROM t9 ORDER BY a; SELECT * FROM t9;
-- }
SELECT * FROM t1 ORDER BY a; SELECT * FROM t1;
SELECT * FROM t2 ORDER BY a; SELECT * FROM t2;
SELECT * FROM t3 ORDER BY a; SELECT * FROM t3;
SELECT * FROM t4 ORDER BY a; SELECT * FROM t4;
SELECT * FROM t5 ORDER BY a; SELECT * FROM t5;
SELECT * FROM t6 ORDER BY a; SELECT * FROM t6;
SELECT * FROM t7 ORDER BY a; SELECT * FROM t7;
SELECT * FROM t8 ORDER BY a; SELECT * FROM t8;
SELECT * FROM t9 ORDER BY a; SELECT * FROM t9;