-- progress.test
-- 
-- execsql {
--   BEGIN;
--   CREATE TABLE t1(a);
--   INSERT INTO t1 VALUES(1);
--   INSERT INTO t1 VALUES(2);
--   INSERT INTO t1 VALUES(3);
--   INSERT INTO t1 VALUES(4);
--   INSERT INTO t1 VALUES(5);
--   INSERT INTO t1 VALUES(6);
--   INSERT INTO t1 VALUES(7);
--   INSERT INTO t1 VALUES(8);
--   INSERT INTO t1 VALUES(9);
--   INSERT INTO t1 VALUES(10);
--   COMMIT;
-- }
BEGIN;
CREATE TABLE t1(a);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);
INSERT INTO t1 VALUES(3);
INSERT INTO t1 VALUES(4);
INSERT INTO t1 VALUES(5);
INSERT INTO t1 VALUES(6);
INSERT INTO t1 VALUES(7);
INSERT INTO t1 VALUES(8);
INSERT INTO t1 VALUES(9);
INSERT INTO t1 VALUES(10);
COMMIT;