-- savepoint.test
-- 
-- execsql {
--     DROP TABLE IF EXISTS t1;
--     DROP TABLE IF EXISTS t2;
--     DROP TABLE IF EXISTS t3;
-- }
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;