-- selectB.test
-- 
-- execsql {
--       SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT d FROM t2)
--       EXCEPT 
--       SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT d FROM t2)
-- }
SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT d FROM t2)
EXCEPT 
SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT d FROM t2)