-- selectB.test
-- 
-- execsql {
--       SELECT * FROM (SELECT e FROM t2 UNION ALL SELECT f FROM t2)
--       INTERSECT 
--       SELECT c FROM t1
--       ORDER BY 1
-- }
SELECT * FROM (SELECT e FROM t2 UNION ALL SELECT f FROM t2)
INTERSECT 
SELECT c FROM t1
ORDER BY 1