-- select4.test
-- 
-- execsql {
--     SELECT NULL UNION SELECT NULL UNION
--     SELECT 1 UNION SELECT 2 AS 'x'
--     ORDER BY x;
-- }
SELECT NULL UNION SELECT NULL UNION
SELECT 1 UNION SELECT 2 AS 'x'
ORDER BY x;