-- select4.test
-- 
-- execsql {
--     SELECT NULL UNION ALL SELECT NULL UNION ALL
--     SELECT 1 UNION ALL SELECT 2 AS 'x'
--     ORDER BY x;
-- }
SELECT NULL UNION ALL SELECT NULL UNION ALL
SELECT 1 UNION ALL SELECT 2 AS 'x'
ORDER BY x;