-- sort.test
-- 
-- execsql {
--     CREATE TABLE t7(c INTEGER PRIMARY KEY);
--     INSERT INTO t7 VALUES(1);
--     INSERT INTO t7 VALUES(2);
--     INSERT INTO t7 VALUES(3);
--     INSERT INTO t7 VALUES(4);
-- }
CREATE TABLE t7(c INTEGER PRIMARY KEY);
INSERT INTO t7 VALUES(1);
INSERT INTO t7 VALUES(2);
INSERT INTO t7 VALUES(3);
INSERT INTO t7 VALUES(4);