-- subquery.test
-- 
-- execsql {
--     BEGIN;
--     CREATE TABLE t1(a,b);
--     INSERT INTO t1 VALUES(1,2);
--     INSERT INTO t1 VALUES(3,4);
--     INSERT INTO t1 VALUES(5,6);
--     INSERT INTO t1 VALUES(7,8);
--     CREATE TABLE t2(x,y);
--     INSERT INTO t2 VALUES(1,1);
--     INSERT INTO t2 VALUES(3,9);
--     INSERT INTO t2 VALUES(5,25);
--     INSERT INTO t2 VALUES(7,49);
--     COMMIT;
-- }
BEGIN;
CREATE TABLE t1(a,b);
INSERT INTO t1 VALUES(1,2);
INSERT INTO t1 VALUES(3,4);
INSERT INTO t1 VALUES(5,6);
INSERT INTO t1 VALUES(7,8);
CREATE TABLE t2(x,y);
INSERT INTO t2 VALUES(1,1);
INSERT INTO t2 VALUES(3,9);
INSERT INTO t2 VALUES(5,25);
INSERT INTO t2 VALUES(7,49);
COMMIT;