-- tkt-4a03edc4c8.test
-- 
-- db eval {
--     CREATE TABLE t1(
--       a INTEGER PRIMARY KEY ON CONFLICT REPLACE,
--       b UNIQUE ON CONFLICT FAIL
--     );
--     INSERT INTO t1 VALUES(1, 1);
--     INSERT INTO t1 VALUES(2, 2);
-- }
CREATE TABLE t1(
a INTEGER PRIMARY KEY ON CONFLICT REPLACE,
b UNIQUE ON CONFLICT FAIL
);
INSERT INTO t1 VALUES(1, 1);
INSERT INTO t1 VALUES(2, 2);