-- tkt-cbd054fa6b.test
-- 
-- db eval {
--     CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT UNIQUE NOT NULL);
--     CREATE INDEX t1_x ON t1(b);
--     INSERT INTO t1 VALUES (NULL, '');
--     INSERT INTO t1 VALUES (NULL, 'A');
--     INSERT INTO t1 VALUES (NULL, 'B');
--     INSERT INTO t1 VALUES (NULL, 'C');
--     INSERT INTO t1 VALUES (NULL, 'D');
--     INSERT INTO t1 VALUES (NULL, 'E');
--     INSERT INTO t1 VALUES (NULL, 'F');
--     INSERT INTO t1 VALUES (NULL, 'G');
--     INSERT INTO t1 VALUES (NULL, 'H');
--     INSERT INTO t1 VALUES (NULL, 'I');
--     SELECT count(*) FROM t1;
-- }
CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT UNIQUE NOT NULL);
CREATE INDEX t1_x ON t1(b);
INSERT INTO t1 VALUES (NULL, '');
INSERT INTO t1 VALUES (NULL, 'A');
INSERT INTO t1 VALUES (NULL, 'B');
INSERT INTO t1 VALUES (NULL, 'C');
INSERT INTO t1 VALUES (NULL, 'D');
INSERT INTO t1 VALUES (NULL, 'E');
INSERT INTO t1 VALUES (NULL, 'F');
INSERT INTO t1 VALUES (NULL, 'G');
INSERT INTO t1 VALUES (NULL, 'H');
INSERT INTO t1 VALUES (NULL, 'I');
SELECT count(*) FROM t1;