-- tkt-cbd054fa6b.test
-- 
-- db eval {
--     DROP TABLE t1;
--     CREATE TABLE t1(a INTEGER PRIMARY KEY, b BLOB UNIQUE NOT NULL);
--     CREATE INDEX t1_x ON t1(b);
--     INSERT INTO t1 VALUES(NULL, X'');
--     INSERT INTO t1 VALUES(NULL, X'41');
--     INSERT INTO t1 VALUES(NULL, X'42');
--     INSERT INTO t1 VALUES(NULL, X'43');
--     INSERT INTO t1 VALUES(NULL, X'44');
--     INSERT INTO t1 VALUES(NULL, X'45');
--     INSERT INTO t1 VALUES(NULL, X'46');
--     INSERT INTO t1 VALUES(NULL, X'47');
--     INSERT INTO t1 VALUES(NULL, X'48');
--     INSERT INTO t1 VALUES(NULL, X'49');
--     SELECT count(*) FROM t1;
-- }
DROP TABLE t1;
CREATE TABLE t1(a INTEGER PRIMARY KEY, b BLOB UNIQUE NOT NULL);
CREATE INDEX t1_x ON t1(b);
INSERT INTO t1 VALUES(NULL, X'');
INSERT INTO t1 VALUES(NULL, X'41');
INSERT INTO t1 VALUES(NULL, X'42');
INSERT INTO t1 VALUES(NULL, X'43');
INSERT INTO t1 VALUES(NULL, X'44');
INSERT INTO t1 VALUES(NULL, X'45');
INSERT INTO t1 VALUES(NULL, X'46');
INSERT INTO t1 VALUES(NULL, X'47');
INSERT INTO t1 VALUES(NULL, X'48');
INSERT INTO t1 VALUES(NULL, X'49');
SELECT count(*) FROM t1;