-- tkt1644.test
-- 
-- execsql {
--     CREATE TABLE t1(a);
--     INSERT INTO t1 VALUES(1);
--     CREATE TABLE t2(b);
--     INSERT INTO t2 VALUES(99);
--     CREATE TEMP VIEW v1 AS SELECT * FROM t1;
--     SELECT * FROM v1;
-- }
CREATE TABLE t1(a);
INSERT INTO t1 VALUES(1);
CREATE TABLE t2(b);
INSERT INTO t2 VALUES(99);
CREATE TEMP VIEW v1 AS SELECT * FROM t1;
SELECT * FROM v1;