-- tkt2820.test
-- 
-- db eval {
--     CREATE TABLE t1(a INTEGER PRIMARY KEY);
--     INSERT INTO t1 VALUES(1);
--     INSERT INTO t1 VALUES(2);
-- }
CREATE TABLE t1(a INTEGER PRIMARY KEY);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);