-- tkt2643.test
-- 
-- execsql {
--     CREATE TABLE t1(a INTEGER PRIMARY KEY, b UNIQUE, c);
--     INSERT INTO t1 VALUES(1,2,3);
--     INSERT INTO t1 VALUES(2,3,4);
--     ANALYZE;
-- }
CREATE TABLE t1(a INTEGER PRIMARY KEY, b UNIQUE, c);
INSERT INTO t1 VALUES(1,2,3);
INSERT INTO t1 VALUES(2,3,4);
ANALYZE;