-- tkt2832.test
-- 
-- execsql {
--     CREATE TABLE t1(a PRIMARY KEY);
--     INSERT INTO t1 VALUES(2);
--     INSERT INTO t1 VALUES(1);
--     INSERT INTO t1 VALUES(3);
-- }
CREATE TABLE t1(a PRIMARY KEY);
INSERT INTO t1 VALUES(2);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(3);