-- tkt3824.test
-- 
-- db eval {
--     CREATE TABLE t2(a,b,c);
--     INSERT INTO t2 VALUES(1,1,NULL);
--     INSERT INTO t2 VALUES(9,2,NULL);
--     INSERT INTO t2 VALUES(5,2,NULL);
--     INSERT INTO t2 VALUES(123,3,NULL);
--     INSERT INTO t2 VALUES(-10,3,NULL);
--     CREATE UNIQUE INDEX t2bc ON t2(b,c);
-- }
CREATE TABLE t2(a,b,c);
INSERT INTO t2 VALUES(1,1,NULL);
INSERT INTO t2 VALUES(9,2,NULL);
INSERT INTO t2 VALUES(5,2,NULL);
INSERT INTO t2 VALUES(123,3,NULL);
INSERT INTO t2 VALUES(-10,3,NULL);
CREATE UNIQUE INDEX t2bc ON t2(b,c);