-- tkt3824.test
-- 
-- db eval {
--     CREATE TABLE t3(x,y);
--     INSERT INTO t3 SELECT a, b FROM t1;
--     INSERT INTO t3 VALUES(234,567);
--     CREATE UNIQUE INDEX t3y ON t3(y);
--     DELETE FROM t3 WHERE y IS NULL;
--     SELECT * FROM t3;
-- }
CREATE TABLE t3(x,y);
INSERT INTO t3 SELECT a, b FROM t1;
INSERT INTO t3 VALUES(234,567);
CREATE UNIQUE INDEX t3y ON t3(y);
DELETE FROM t3 WHERE y IS NULL;
SELECT * FROM t3;