-- tkt3581.test
-- 
-- db eval {
--     CREATE TABLE t1(a INTEGER PRIMARY KEY, b, c);
--     INSERT INTO t1 VALUES(0,544,846);
--     INSERT INTO t1 VALUES(1,345,51);
--     CREATE TABLE t2(a INTEGER PRIMARY KEY, b, c);
--     INSERT INTO t2 SELECT * FROM t1;
--     CREATE INDEX i2 on t2(c);
-- }
CREATE TABLE t1(a INTEGER PRIMARY KEY, b, c);
INSERT INTO t1 VALUES(0,544,846);
INSERT INTO t1 VALUES(1,345,51);
CREATE TABLE t2(a INTEGER PRIMARY KEY, b, c);
INSERT INTO t2 SELECT * FROM t1;
CREATE INDEX i2 on t2(c);