-- trigger2.test
-- 
-- execsql {
--     CREATE TRIGGER r2 INSTEAD OF INSERT ON v1 BEGIN
--       INSERT INTO v1log VALUES(NULL,NEW.x,NULL,NEW.y,NULL,NEW.z);
--     END;
--     DELETE FROM v1log;
--     INSERT INTO v1 VALUES(1,2,3);
--     SELECT * FROM v1log;
-- }
CREATE TRIGGER r2 INSTEAD OF INSERT ON v1 BEGIN
INSERT INTO v1log VALUES(NULL,NEW.x,NULL,NEW.y,NULL,NEW.z);
END;
DELETE FROM v1log;
INSERT INTO v1 VALUES(1,2,3);
SELECT * FROM v1log;