-- triggerC.test
-- 
-- execsql {
--     DROP TABLE t1;
--     CREATE TABLE cnt(n);
--     INSERT INTO cnt VALUES(0);
--     CREATE TABLE t1(a INTEGER PRIMARY KEY, b UNIQUE, c, d, e);
--     CREATE INDEX t1cd ON t1(c,d);
--     CREATE TRIGGER t1r1 AFTER UPDATE ON t1 BEGIN UPDATE cnt SET n=n+1; END;
--     INSERT INTO t1 VALUES(1,2,3,4,5);
--     INSERT INTO t1 VALUES(6,7,8,9,10);
--     INSERT INTO t1 VALUES(11,12,13,14,15);
-- }
DROP TABLE t1;
CREATE TABLE cnt(n);
INSERT INTO cnt VALUES(0);
CREATE TABLE t1(a INTEGER PRIMARY KEY, b UNIQUE, c, d, e);
CREATE INDEX t1cd ON t1(c,d);
CREATE TRIGGER t1r1 AFTER UPDATE ON t1 BEGIN UPDATE cnt SET n=n+1; END;
INSERT INTO t1 VALUES(1,2,3,4,5);
INSERT INTO t1 VALUES(6,7,8,9,10);
INSERT INTO t1 VALUES(11,12,13,14,15);