-- triggerC.test
-- 
-- execsql {
--     CREATE TABLE t23(x PRIMARY KEY);
-- 
--     CREATE TRIGGER t23a AFTER INSERT ON t23 BEGIN
--       INSERT INTO t23 VALUES(new.x + 1);
--     END;
-- 
--     CREATE TRIGGER t23b BEFORE INSERT ON t23 BEGIN
--       SELECT CASE WHEN new.x>500
--                   THEN RAISE(IGNORE)
--                   ELSE NULL END;
--     END;
-- 
--     INSERT INTO t23 VALUES(1);
--     SELECT count(*) FROM t23;
-- }
CREATE TABLE t23(x PRIMARY KEY);
CREATE TRIGGER t23a AFTER INSERT ON t23 BEGIN
INSERT INTO t23 VALUES(new.x + 1);
END;
CREATE TRIGGER t23b BEFORE INSERT ON t23 BEGIN
SELECT CASE WHEN new.x>500
THEN RAISE(IGNORE)
ELSE NULL END;
END;
INSERT INTO t23 VALUES(1);
SELECT count(*) FROM t23;