-- triggerA.test
-- 
-- db eval {
--     CREATE TABLE t1(x INTEGER PRIMARY KEY, y TEXT UNIQUE);
--     CREATE TABLE t2(a INTEGER PRIMARY KEY, b INTEGER UNIQUE, c TEXT);
-- }
CREATE TABLE t1(x INTEGER PRIMARY KEY, y TEXT UNIQUE);
CREATE TABLE t2(a INTEGER PRIMARY KEY, b INTEGER UNIQUE, c TEXT);