-- update.test
-- 
-- execsql {
--     BEGIN;
--     CREATE TABLE t2(a);
--     INSERT INTO t2 VALUES(1);
--     INSERT INTO t2 VALUES(2);
--     INSERT INTO t2 SELECT a+2 FROM t2;
--     INSERT INTO t2 SELECT a+4 FROM t2;
--     INSERT INTO t2 SELECT a+8 FROM t2;
--     INSERT INTO t2 SELECT a+16 FROM t2;
--     INSERT INTO t2 SELECT a+32 FROM t2;
--     INSERT INTO t2 SELECT a+64 FROM t2;
--     INSERT INTO t2 SELECT a+128 FROM t2;
--     INSERT INTO t2 SELECT a+256 FROM t2;
--     INSERT INTO t2 SELECT a+512 FROM t2;
--     INSERT INTO t2 SELECT a+1024 FROM t2;
--     COMMIT;
--     SELECT count(*) FROM t2;
-- }
BEGIN;
CREATE TABLE t2(a);
INSERT INTO t2 VALUES(1);
INSERT INTO t2 VALUES(2);
INSERT INTO t2 SELECT a+2 FROM t2;
INSERT INTO t2 SELECT a+4 FROM t2;
INSERT INTO t2 SELECT a+8 FROM t2;
INSERT INTO t2 SELECT a+16 FROM t2;
INSERT INTO t2 SELECT a+32 FROM t2;
INSERT INTO t2 SELECT a+64 FROM t2;
INSERT INTO t2 SELECT a+128 FROM t2;
INSERT INTO t2 SELECT a+256 FROM t2;
INSERT INTO t2 SELECT a+512 FROM t2;
INSERT INTO t2 SELECT a+1024 FROM t2;
COMMIT;
SELECT count(*) FROM t2;