-- vacuum2.test
-- 
-- execsql {
--     CREATE TABLE t1(x INTEGER PRIMARY KEY AUTOINCREMENT, y);
--     DROP TABLE t1;
--     VACUUM;
-- }
CREATE TABLE t1(x INTEGER PRIMARY KEY AUTOINCREMENT, y);
DROP TABLE t1;
VACUUM;