-- view.test
-- 
-- execsql {
--     DROP TABLE IF EXISTS t1;
--     DROP VIEW IF EXISTS v1;
--     CREATE TABLE t1(c1);
--     CREATE VIEW v1 AS SELECT c1 FROM (SELECT t1.c1 FROM t1);
-- }
DROP TABLE IF EXISTS t1;
DROP VIEW IF EXISTS v1;
CREATE TABLE t1(c1);
CREATE VIEW v1 AS SELECT c1 FROM (SELECT t1.c1 FROM t1);