-- view.test
-- 
-- execsql {
--     INSERT INTO t2 SELECT * FROM t2 WHERE a<5;
--     INSERT INTO t2 SELECT * FROM t2 WHERE a<4;
--     INSERT INTO t2 SELECT * FROM t2 WHERE a<3;
--     SELECT DISTINCT count(*) FROM t2 GROUP BY a ORDER BY 1;
-- }
INSERT INTO t2 SELECT * FROM t2 WHERE a<5;
INSERT INTO t2 SELECT * FROM t2 WHERE a<4;
INSERT INTO t2 SELECT * FROM t2 WHERE a<3;
SELECT DISTINCT count(*) FROM t2 GROUP BY a ORDER BY 1;