-- vtab6.test
-- 
-- execsql {
--     BEGIN;
--     INSERT INTO t6 VALUES(NULL);
--     INSERT INTO t6 VALUES(NULL);
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     INSERT INTO t6 SELECT * FROM t6;
--     COMMIT;
-- }
BEGIN;
INSERT INTO t6 VALUES(NULL);
INSERT INTO t6 VALUES(NULL);
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
INSERT INTO t6 SELECT * FROM t6;
COMMIT;