-- vtab6.test
-- 
-- execsql {
--     INSERT INTO t4 VALUES(2,3,4);
--     INSERT INTO t4 VALUES(3,4,5);
--     INSERT INTO t4 VALUES(4,5,6);
--     SELECT * FROM t4;
-- }
INSERT INTO t4 VALUES(2,3,4);
INSERT INTO t4 VALUES(3,4,5);
INSERT INTO t4 VALUES(4,5,6);
SELECT * FROM t4;