-- vtab6.test
-- 
-- execsql {
--       CREATE VIEW v13 AS SELECT * FROM t13 WHERE b>0;
--       SELECT * FROM t12 NATURAL LEFT JOIN t13
--         EXCEPT
--         SELECT * FROM t12 NATURAL LEFT JOIN v13;
-- }
CREATE VIEW v13 AS SELECT * FROM t13 WHERE b>0;
SELECT * FROM t12 NATURAL LEFT JOIN t13
EXCEPT
SELECT * FROM t12 NATURAL LEFT JOIN v13;