-- vtab6.test
-- 
-- execsql {
--     INSERT INTO t3 VALUES(2,3,4);
--     INSERT INTO t3 VALUES(3,4,5);
--     INSERT INTO t3 VALUES(4,5,6);
--     SELECT * FROM t3;
-- }
INSERT INTO t3 VALUES(2,3,4);
INSERT INTO t3 VALUES(3,4,5);
INSERT INTO t3 VALUES(4,5,6);
SELECT * FROM t3;