-- wal.test
-- 
-- execsql { 
--     PRAGMA journal_mode = WAL;
--     CREATE TABLE t1(a, b);
--     INSERT INTO t1 VALUES(1, 2);
--     INSERT INTO t1 VALUES(3, 4);
--     INSERT INTO t1 VALUES(5, 6);
--     INSERT INTO t1 VALUES(7, 8);
--     INSERT INTO t1 VALUES(9, 10);
--     INSERT INTO t1 VALUES(11, 12);
-- }
PRAGMA journal_mode = WAL;
CREATE TABLE t1(a, b);
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t1 VALUES(7, 8);
INSERT INTO t1 VALUES(9, 10);
INSERT INTO t1 VALUES(11, 12);