-- wal6.test
-- 
-- execsql {
-- 	    CREATE TABLE t1(a INTEGER PRIMARY KEY, b);
-- 	    INSERT INTO t1 VALUES(1,2);
-- 	    SELECT * FROM t1;
-- }
CREATE TABLE t1(a INTEGER PRIMARY KEY, b);
INSERT INTO t1 VALUES(1,2);
SELECT * FROM t1;