-- where8.test
-- 
-- execsql {
--     DROP INDEX IF EXISTS i5;
--     DROP INDEX IF EXISTS i6;
--     DROP INDEX IF EXISTS i7;
--     DROP INDEX IF EXISTS i8;
-- }
DROP INDEX IF EXISTS i5;
DROP INDEX IF EXISTS i6;
DROP INDEX IF EXISTS i7;
DROP INDEX IF EXISTS i8;