-- where.test
-- 
-- execsql {
--     CREATE TEMP TABLE foo(idx INTEGER);
--     INSERT INTO foo VALUES(1);
--     INSERT INTO foo VALUES(1);
--     INSERT INTO foo VALUES(1);
--     INSERT INTO foo VALUES(2);
--     INSERT INTO foo VALUES(2);
--     CREATE TEMP TABLE bar(stuff INTEGER);
--     INSERT INTO bar VALUES(100);
--     INSERT INTO bar VALUES(200);
--     INSERT INTO bar VALUES(300);
-- }
CREATE TEMP TABLE foo(idx INTEGER);
INSERT INTO foo VALUES(1);
INSERT INTO foo VALUES(1);
INSERT INTO foo VALUES(1);
INSERT INTO foo VALUES(2);
INSERT INTO foo VALUES(2);
CREATE TEMP TABLE bar(stuff INTEGER);
INSERT INTO bar VALUES(100);
INSERT INTO bar VALUES(200);
INSERT INTO bar VALUES(300);